import math
print("Введите диаметр трубы=")
d=int(input())
print("Введите радиус отвода=")
r=int(input())
ucho=(d/math.tan(1.37))
srez=(math.sqrt(d**2+ucho**2))
segment_dlin=(2*((r+d/2)/math.tan(1.37)))
segment_kor=segment_dlin-(2*ucho)
print("Ухо=%s" % ucho )
print("Срез=%s" % srez )
print("Длинная сторона сегмента=%s" % segment_dlin)
print("Короткая сторона сегмента=%s" % segment_kor)
import turtle
t=turtle.Pen()
t.pensize(5)
t.left(180)
t.up()
t.forward(200)
t.right(90)
t.down()
t.forward(150)
t.right(90)          
t.forward(d)
t.right(90)
t.forward(150-ucho)
t.right(78.75)
t.forward(srez)
t.left(101.25)
for i in range(0,3):
    t.forward(segment_dlin)
    t.left(101.25)
    t.forward(srez)
    t.left(78.78)
    t.forward(segment_kor)
    t.left(78.78)
    t.up()
    t.forward(srez)
    t.left(101.25)
    t.forward(segment_dlin)
    t.left(22.5)
    t.down()

t.forward(150)
t.left(90)
t.forward(d)
t.left(90)
t.forward(150-ucho)
t.up()
t.right(90)
t.forward(150)
